baseURL = "http://eliudcdelgado.com"
title = "Eliud C. Delgado"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "es"

[params.info]
description = "Minimalist theme for Hugo"
title404 = "Nothing's here!"

[params.assets]
favicon = "images/logo.svg"
logo = "images/logo.svg"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Eliud C. Delgado"
startYear = "2018"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "02 Jan, 2006"
listDateFormat = "02 Jan, 2006"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideSocialMenu = false
showReadingTime = true
taxonomyCloudShuffle = true
accentColor = "#1F88F2"

[params.sidebar]
enable = true

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about","taxonomy_cloud"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "_eliud" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = "hola@eliudcdelgado.com"
facebook = "eliud.c.delgado"
github = "eliud-c-delgado"
instagram = "_eliud"
linkedin = "eliudcdelgado"
twitter = "_eliud"
telegram = "eliudcdelgado"

[params.comments]
enable = false

[params.comments.staticman]
enable = true
apiEndpoint = "https://api.staticman.net/v2/entry"
maxDepth = 2

[params.comments.staticman.github]
username = "eliud-c-delgado"
repository = "personal-site"
branch = "master"

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "personal-site"
weight = -10
identifier = "repository"
url = "https://github.com/eliud-c-delgado/personal-site"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.es]
lang = "es"
languageName = "Español"
weight = 1

[languages.en]
lang = "en"
languageName = "English"
weight = 2
